name: ml311
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - alembic=1.8.1=py311haa95532_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boost=1.78.0=py311h12feb9d_5
  - boost-cpp=1.78.0=h9f4b32c_4
  - bottleneck=1.3.7=py311hd7041d2_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - brotli-python=1.0.9=py311hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.11.26=haa95532_0
  - cairo=1.18.0=h32b962e_3
  - certifi=2024.12.14=py311haa95532_0
  - chardet=4.0.0=py311haa95532_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cloudpickle=3.0.0=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - colorlog=5.0.1=py311haa95532_1
  - comm=0.2.1=py311haa95532_0
  - contourpy=1.2.0=py311h59b6b97_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py311hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py311haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h5da7b33_0
  - font-ttf-dejavu-sans-mono=2.37=0
  - font-ttf-inconsolata=2.000=0
  - font-ttf-source-code-pro=2.030=0
  - font-ttf-ubuntu=0.83=0
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py311h2bbff1b_0
  - freetype=2.12.1=hdaf720e_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - glib=2.80.3=h7025463_2
  - glib-tools=2.80.3=h4394cf3_2
  - greenlet=3.0.1=py311hd77b12b_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=75.1=he0c23c2_0
  - idna=3.7=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.28.0=py311haa95532_0
  - ipython=8.25.0=py311haa95532_0
  - jedi=0.19.1=py311haa95532_0
  - joblib=1.4.2=py311haa95532_0
  - jupyter_client=8.6.0=py311haa95532_0
  - jupyter_core=5.7.2=py311haa95532_0
  - kiwisolver=1.4.4=py311hd77b12b_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libdeflate=1.21=h2466b09_0
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.80.3=h7025463_2
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.3=h827c3e9_0
  - libpng=1.6.43=h19919ed_0
  - libsodium=1.0.18=h62dcd97_0
  - libsqlite=3.46.1=h2466b09_0
  - libtiff=4.6.0=hb151862_4
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.16=h013a479_1
  - libxgboost=2.0.3=h5da7b33_0
  - libxml2=2.12.7=h0f24e4e_4
  - libzlib=1.3.1=h2466b09_1
  - lightgbm=4.5.0=py311h5da7b33_0
  - llvmlite=0.41.0=py311hf2fb9eb_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.2.3=py311haa95532_0
  - markupsafe=2.1.3=py311h2bbff1b_0
  - matplotlib-base=3.9.2=py311h472561b_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.10=py311h827c3e9_0
  - mkl_random=1.2.7=py311hea22821_0
  - msys2-conda-epoch=20160418=1
  - nest-asyncio=1.6.0=py311haa95532_0
  - numba=0.58.1=py311hf62ec03_0
  - numexpr=2.8.7=py311h1fcbade_0
  - numpy=1.26.4=py311hdab7c0b_0
  - numpy-base=1.26.4=py311hd01c5d8_0
  - openjpeg=2.5.2=hae555c5_0
  - openpyxl=3.1.5=py311h827c3e9_0
  - openssl=3.3.2=h2466b09_0
  - optuna=3.6.1=pyhd8ed1ab_0
  - packaging=24.1=py311haa95532_0
  - pandas=2.2.2=py311hea22821_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.44=h3d7b363_2
  - pillow=10.4.0=py311h5592be9_0
  - pip=24.2=py311haa95532_0
  - pixman=0.43.4=h63175ca_0
  - platformdirs=3.10.0=py311haa95532_0
  - prompt-toolkit=3.0.43=py311haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h2bbff1b_0
  - pthread-stubs=0.3=h3c9f919_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=2.0.3=py311haa95532_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycairo=1.23.0=py311had253c0_0
  - pygments=2.15.1=py311haa95532_1
  - pyparsing=3.1.2=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.9=h631f459_0_cpython
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2024.1=py311haa95532_0
  - pywin32=305=py311h2bbff1b_0
  - pyyaml=6.0.1=py311h2bbff1b_0
  - pyzmq=25.1.2=py311hd77b12b_0
  - rdkit=2022.09.5=py311h5f60fae_0
  - reportlab=4.2.2=py311he736701_0
  - requests=2.32.3=py311haa95532_1
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - scikit-learn=1.5.1=py311hea22821_0
  - scipy=1.13.1=py311h9f229c6_0
  - seaborn=0.13.2=py311haa95532_0
  - setuptools=72.1.0=py311haa95532_0
  - shap=0.42.1=py311hf62ec03_0
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.7=pyhd3eb1b0_0
  - sqlalchemy=2.0.34=py311h54f65d0_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py311h746a85d_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4.1=py311h827c3e9_0
  - tqdm=4.66.5=py311h746a85d_0
  - traitlets=5.14.3=py311haa95532_0
  - typing-extensions=4.11.0=py311haa95532_0
  - typing_extensions=4.11.0=py311haa95532_0
  - tzdata=2024a=h04d1e81_0
  - ucrt=10.0.20348.0=haa95532_0
  - unicodedata2=15.1.0=py311h2bbff1b_0
  - urllib3=2.2.3=py311haa95532_0
  - vc=14.40=h2eaa2aa_0
  - vc14_runtime=14.40.33810=hcc2c482_20
  - vs2015_runtime=14.40.33810=h3bf8584_20
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.43.0=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - xgboost=2.0.3=py311haa95532_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.3.1=h2466b09_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - pubchempy==1.0.4
      - py3dmol==2.4.2
prefix: D:\Software\anaconda\envs\ml311
